### PR TITLE
RPM updates

### PR DESCRIPTION
**Pull request by marcosfrm**
Do not shoot ourselves in the foot with this thing. Nothing will work on different paths.

https://docs.fedoraproject.org/en-US/packaging-guidelines/#_relocatable_packages

### CODE REVIEW

**Comment by kbernhagen** [comment]
I don't see `prefix` being used for deb either.
Should it be removed from client `SConstruct`?

**Comment by marcosfrm** [comment]
If not used anywhere else, yes. I did not check.

**Comment by marcosfrm** [comment]
`if key is 'documents':` is preferred over `if key == 'documents':` right?

**Comment by jcoffland** [comment]
``==`` is more familiar to me.  Also, they are not quite the same thing:

> The ``==`` operator compares the value or equality of two objects, whereas the Python ``is`` operator checks whether two variables point to the same object in memory.

In this case it probably doesn't matter.

In general, I prefer to reduce the number of lines of code where ever reasonable but I always enforce an 80-column limit to all lines.  The later is a bit old-school but I maintain this consistency through all my code.  It allows me to view 3 files side-by-side on one screen.  This improves my ability to quickly compare different parts of the code.

**Pull request merged**
