### PR TITLE
Update Win getOSVersion()

### PR DESCRIPTION
**Pull request by kbernhagen**
WIP

This tested ok on Win 10 (unlicensed) and 7 Pro.

GetVersionEx() is deprecated and never gives version greater than 6.2.
Some other methods exist, but can lie based on app manifest.

### CODE REVIEW

**Comment by kbernhagen** [comment]
I don't know if this would fail on a non-Pro install of Windows.

It might be reasonable to keep the old code as a fallback.

**Comment by marcosfrm** [comment]
`RtlGetNtVersionNumbers()` (available since Windows XP) is better:

https://github.com/golang/sys/commit/fb81701db80f1745f51259b1f286de3fe2ec80c8
https://www.geoffchappell.com/studies/windows/win32/ntdll/api/ldrinit/getntversionnumbers.htm

Example:

https://dennisbabkin.com/blog/?t=how-to-tell-the-real-version-of-windows-your-app-is-running-on

**Comment by kbernhagen** [comment]
Yes, better, thanks.
I will use that. With a fallback, as suggested,?because it’s undocumented.

**Comment by marcosfrm** [comment]
These undocumented Windows APIs will exist until hell freezes over. 🤣

**Comment by kbernhagen** [comment]
Although seemingly working, this was a WIP.
I’ll make improvements in another PR.

**Pull request merged**
