### PR TITLE
Add support for AArch64 to CPUID

### PR DESCRIPTION
**Pull request by dmsck**

### CODE REVIEW

**Comment by jcoffland** [comment]
I'm not a big fan of all the ifdefs.  The ``CPUID`` class is unavoidably Intel specific.  I'd rather see a new ``ARMCPUID`` class with one ore more enums (ARMFeature) for the features.  For example, see https://github.com/CauldronDevelopmentLLC/cbang/blob/master/src/cbang/enum/CPUFeature.h.

**Comment by dmsck** [comment]
> I'm not a big fan of all the ifdefs.

Me neither. But if I create the new `ARMCPUID` class, we'll need to put the ifdefs in all the places where we currently use `CPUID`, is not? Is it really better approach than concentrating all the ifdefs in one place, in the `CPUID` implementation?

With the new `ARMCPUID` class, the usage will always be something like that:

```c
#ifdef __aarch64__
ARMCPUID cpuid;
#else
CPUID cpuid;
#endif
```

For me, it looks ugly. What do you think? Is it worth doing it this way?

**Comment by kbernhagen** [comment]
IFDEFS will be broken on Apple Silicon Macs, where an intel binary might be running translated by Rosetta 2.

Shouldn't CPUID become an abstract base class, with subclasses IntelCPUID and ARMCPUID?

**Comment by kbernhagen** [comment]
The "fix iteration" commit looks wrong to me, because i is pre-decremented.

**Comment by kbernhagen** [comment]
Oops. I’m totally off base with that last comment. 

I still wonder what the correct range of i should be. 

If the original range of cores .. 1 is wrong, I would expect it should be (cores - 1) .. 0.

**Comment by jcoffland** [comment]
> Shouldn't CPUID become an abstract base class, with subclasses IntelCPUID and ARMCPUID?

I agree but the whole CPUID interface is very Intel specific.  It would need to be reworked and so would the code that uses it.

**Comment by dmsck** [comment]
> If the original range of cores .. 1 is wrong, I would expect it should be (cores - 1) .. 0.

You're right. The range should be (cores - 1) .. 0. However, practically it works even with cores .. 0 range, because it checks for existence of the /sys/devices/system/cpu/cpu%d/regs/identification/midr_el1 file, and skips it if not found.

I agree that it should be fixed though, to avoid any confusion. I'll do it little later.

**Comment by dmsck** [comment]
I've just re-created the commit, which adds AArch64 support to the CPUID class (this time, supporting both Linux and Mac Arm hosts). I don't know if it's going to be accepted, but currently this patch contains some useful code, which works properly with ARM CPUs. I don't want to lose it.

So let's discuss it again and either accept this patch or define an alternative way of implementing AArch64 support in cbang.

**Comment by jcoffland** [comment]
I'd like to go a bit different route here.  Here's what I propose:

  * Integrate CPU feature code for ARM from here: https://github.com/google/cpu_features and this PR.
  * Create a more general CPUInfo class to replace CPUID.
  * Create CPUInfoIntel and CPUInfoArm implementations.  CPUInfoIntel would be very similar the current CPUID.
  * Replace CPUIDTool with CPUInfoTool.
  * Update the dependent code.  (fah-client, fah-client-bastet & fah-assign)

https://github.com/google/cpu_features doesn't seem to address ARM for macOS or detect ARM CPU models so there's more work to be done there.

fah-client needs several CPU features flag sets.  The flags will be different for ARM and Intel but they exist for both and could just consist of several 32-bit or 64-bit flag sets named ``features1``, ``features2``, etc.

**Comment by dmsck** [comment]
Sounds like a plan! I'll try to re-work this PR in the suggested direction.

> https://github.com/google/cpu_features doesn't seem to address ARM for macOS or detect ARM CPU models so there's more work to be done there.

No worries, I've already implemented the code, which collects the ARM CPU features by using macOS-specific API. It won't be hard to integrate it with the `cpu_features` interface.

**Comment by kbernhagen** [comment]
cpu_features is Apache License 2.0. Will that be a problem?

**Comment by jcoffland** [comment]
I don't think that's a problem.  C! is Open-Source.  How we handle it depends a bit on if we straight copy code or just use it as a guide.  In the former case, we will need to make sure to add a license notice to C!.

**Comment by kbernhagen** [comment]
Also possibly of interest:

https://github.com/pytorch/cpuinfo

**Comment by jcoffland** [comment]
Thanks Dmitry

**Pull request merged**
