### PR TITLE
cross-compile support

### PR DESCRIPTION
**Pull request by sgn**
Hi,

I refactor the build system to support cross compiling.

It's nice to have this upstream.

### CODE REVIEW

**Comment by jcoffland** [comment]
The ``sizeof`` check failed on GCC so I dropped that part of your PR.  If you have a version that works on GCC, please feel free to submit a new PR.

**Comment by jcoffland** [comment]
Unfortunately the OpenSSL checks also fail in GCC.  I had to revert them as well.

**Comment by sgn** [comment]
Can you provide your gcc version?
I'm also using gcc, at version 9.3.0,
albeit, I'm using LibreSSL, which reports ssl version to 2.0.0

**Comment by jcoffland** [comment]
```
$ gcc --version
gcc (Debian 9.2.1-22) 9.2.1 20200104
```

**Comment by sgn** [comment]
Could you please provide your config.log?
Travis (gcc 7.4.0) works.
https://travis-ci.org/github/sgn/cbang/jobs/688184499#L344
https://travis-ci.org/github/sgn/cbang/jobs/688184499#L414

I'm setting up a Debian 10.4.0 qemu image now.

**Comment by sgn** [comment]
Debian Buster stable (comes with gcc 8.3.0 and OpenSSL 1.1.1d) also works fine for me.
I think I'll need your config.log to check whether it have any different configuration from me.

**Comment by jcoffland** [comment]
I tried this again.  The checks you provided don't work with gcc or clang as far as I can tell.  This program always compiles:

```
int main() {
  int a[0];
  a[0] = 0;
  return 0;
}
```

It does yield a warning about ``a`` being set but not used.  It does not bounds check the array.  Even adding the ``-Warray-bounds`` option makes no difference.

So your builds pass but the check for OpenSSL would always succeed even if the wrong version was installed.

The other fixes are great though.

**Comment by sgn** [comment]
On 2020-05-31 15:31:30-0700, Joseph Coffland <notifications@github.com> wrote:
> I tried this again.  The checks you provided don't work with gcc or clang as far as I can tell.  This program always compiles:
> 
> ```
> int main() {
>   int a[0];
>   a[0] = 0;
>   return 0;
> }
> ```
> 
> It does yield a warning about ``a`` being set but not used.  It does not bounds check the array.  Even adding the ``-Warray-bounds`` option makes no difference.
> 
> So your builds pass but the check for OpenSSL would always succeed even if the wrong version was installed.
> 
> The other fixes are great though.

Thanks for your check, yes, it's my bad.

The fix very simple. Should I create new PR or can I just push it
here?

-- 
Danh

**Comment by sgn** [comment]
Anyway, does the sizeof check works?
I've checked it, but I think the only different is current version
return yes/no.

And my version return positive number on OK, and zero on failure.
Is it equivalence?

-- 
Danh

**Pull request merged**
