### PR TITLE
Fix system zlib detection

### PR DESCRIPTION
**Pull request by marcosfrm**

### CODE REVIEW

**Comment by jcoffland** [comment]
This isn't correct.  It must match the name ``src/zlib`` which is always lower case.

This may have worked because changing case would force the local static lib not to be used because it would not be found.  Note, that cbang often has ``mostly_static`` set to true which causes it to prefer static libraries over dynamic ones.

**Comment by marcosfrm** [comment]
`env.CBConfigEnabled('zlib')` is never `True` and the bundled static lib is always used.

**Comment by jcoffland** [comment]
I can build with an external zlib lib if I do this:

```sh
cd cbang
rm -rf .scon*
scons disable_local=zlib
cd ../fah-client-bastet
scons disable_local=zlib
```

**Comment by marcosfrm** [comment]
My point is that with `libbz2`, if system dynamic library and headers are present, it will **not** build the bundled one (plain `scons` call, without options). I believe `libz` should behave this way too, but it does not because what is set as "ConfigEnabled" is `ZLib`, not `zlib`:

https://github.com/CauldronDevelopmentLLC/cbang/blob/f13bdea42836f5cd44f08631eff3335350836a1b/config/ZLib/__init__.py#L43

?

**Comment by marcosfrm** [comment]
Is this acceptable?

```diff
diff --git a/SConstruct b/SConstruct
index 28fd9fc7..b1022138 100644
--- a/SConstruct
+++ b/SConstruct
@@ -67,7 +67,8 @@ resources_excludes = []
 for lib in 'zlib bzip2 lz4 sqlite3 expat boost libevent re2 libyaml'.split():
     if lib in disable_local: resources_excludes.append('licenses/%s\\.txt' % lib)
     else:
-        if not env.CBConfigEnabled(lib) or lib in force_local:
+        if not env.CBConfigEnabled('ZLib' if lib == 'zlib' else lib) \
+                or lib in force_local:
             Default(SConscript('src/%s/SConscript' % lib,
                             variant_dir = 'build/' + lib))
 env.Append(RESOURCES_EXCLUDES = resources_excludes)
```

**Comment by jcoffland** [comment]
I believe I've fixed this with the latest commit.

Scons "tools" cannot have the same name as an existing Python module.  ``zlib`` is an Python module so ``config/ZLib`` uses upper case to avoid the name collision. ``cbang/SConstruct`` checks if a local 3rd party lib has been configured by calling ``env.CBConfigEnabled(<name>)``. All of the 3rd party libs in ``src/`` used lower case names so even if the SCons tool in ``config/ZLib`` succeeded the local 3rd party lib ``src/zlib`` would be built and used because the names didn't match.  I fixed this by renaming to ``src/ZLib``.

**Pull request closed without merging**
